import crypto from 'crypto';
import dotenv from 'dotenv';
dotenv.config();

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; // Standard for GCM
const AUTH_TAG_LENGTH = 16;
const KEY = process.env.ENCRYPTION_KEY;

if (!KEY || Buffer.from(KEY, 'hex').length !== 32) {
    console.error('CRITICAL: ENCRYPTION_KEY must be a 32-byte hex string in .env');
    // If we're in dev, we could generate one, but for production it MUST stay consistent
}

const keyBuffer = Buffer.from(KEY, 'hex');

/**
 * Encrypts a string using AES-256-GCM.
 * Returns a colon-separated string: iv:authTag:encryptedData
 */
export const encrypt = (text) => {
    if (!text) return null;
    
    const iv = crypto.randomBytes(IV_LENGTH);
    const cipher = crypto.createCipheriv(ALGORITHM, keyBuffer, iv);
    
    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    
    const authTag = cipher.getAuthTag().toString('hex');
    
    return `${iv.toString('hex')}:${authTag}:${encrypted}`;
};

/**
 * Decrypts a string generated by the encrypt function.
 */
export const decrypt = (encryptedString) => {
    if (!encryptedString) return null;
    
    const [ivHex, authTagHex, encryptedDataHex] = encryptedString.split(':');
    
    if (!ivHex || !authTagHex || !encryptedDataHex) {
        throw new Error('Invalid encrypted data format');
    }
    
    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    const decipher = crypto.createDecipheriv(ALGORITHM, keyBuffer, iv);
    
    decipher.setAuthTag(authTag);
    
    let decrypted = decipher.update(encryptedDataHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    
    return decrypted;
};
